//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STGenetics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderDetailId { get; set; }
        public int Orderpurchaseid { get; set; }
        public int Animalid { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> Discount { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual OrderPurchase OrderPurchase { get; set; }
    }
}
